create database QLVT
use QLVT

create table NHANVIEN(
	MANHANVIEN int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TEN nvarchar(50) not null,
	SDT nvarchar(10), 
	DIACHI nvarchar(max), 
	NGAYSINH date,
	TRANGTHAI bit not null
)

create table VAITRO(
	MAVAITRO int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENVAITRO nvarchar(50) not null unique
)

create table TAIKHOAN(
	EMAIL nvarchar(50) NOT NULL PRIMARY KEY, 
	MATKHAU nvarchar(50) not null, 
	MAVAITRO int FOREIGN KEY REFERENCES VAITRO(MAVAITRO), 
	MANHANVIEN int FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN), 
	TRANGTHAI bit not null
)

create table KHUVUC(
	MAKHUVUC int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENKHUVUC nvarchar(50) not null,
	TRANGTHAI bit not null
)

create table DANHMUC(
	MADANHMUC int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENDANHMUC nvarchar(50) not null,
	MAKHUVUC int FOREIGN KEY REFERENCES KHUVUC(MAKHUVUC),
	TRANGTHAI bit not null
)

create table VATTU(
	MAVATTU int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENVATTU nvarchar(50) not null,
	HINHANH nvarchar(max), 
	DONVI nvarchar(30), 
	MADANHMUC int FOREIGN KEY REFERENCES DANHMUC(MADANHMUC), 
	NHASANXUAT nvarchar(50) not null,
	SOLUONG int not null,
	TRANGTHAI bit not null
)

create table NHACUNGCAP(
	MANHACUNGCAP int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENNHACUNGCAP nvarchar(50) not null,
	SDT nvarchar(10), 
	DIACHI nvarchar(max), 
	TRANGTHAI bit not null
)

create table CONGNHAN(
	MACONGNHAN int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENCONGNHAN nvarchar(50) not null,
	SDT nvarchar(10), 
	DIACHI nvarchar(max), 
	NGAYSINH date,
	TRANGTHAI bit not null
)

create table CONGTRINH(
	MACONGTRINH int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENCONGTRINH nvarchar(50) not null,
	TRANGTHAI bit not null
)

create table KHO(
	MAKHO int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENKHO nvarchar(50) not null unique,
    DIACHI nvarchar(100)
)

create table TRANGTHAIPHIEU(
	MATRANGTHAI int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	TENTRANGTHAI nvarchar(50) not null unique
)

create table PHIEUXUAT(
	MAPHIEUXUAT int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	MANHANVIEN int FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN),
	MACONGNHAN int FOREIGN KEY REFERENCES CONGNHAN(MACONGNHAN),
	THOIGIAN date not null,
	MACONGTRINH int FOREIGN KEY REFERENCES CONGTRINH(MACONGTRINH),
	MATRANGTHAI int FOREIGN KEY REFERENCES TRANGTHAIPHIEU(MATRANGTHAI),
	GHICHU nvarchar(max)
)

create table CHITIETPHIEUXUAT(
	MAVATTU int FOREIGN KEY REFERENCES VATTU(MAVATTU),
	SOLUONG int not null,
	MAPHIEUXUAT int FOREIGN KEY REFERENCES PHIEUXUAT(MAPHIEUXUAT),
)

create table PHIEUNHAP(
	MAPHIEUNHAP int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	MANHANVIEN int FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN),
	MANHACUNGCAP int FOREIGN KEY REFERENCES NHACUNGCAP(MANHACUNGCAP),
	THOIGIAN date not null,
	TONGTIEN bigint not null,
	MATRANGTHAI int FOREIGN KEY REFERENCES TRANGTHAIPHIEU(MATRANGTHAI),
	GHICHU nvarchar(max)
)

create table CHITIETPHIEUNHAP(
	MAVATTU int FOREIGN KEY REFERENCES VATTU(MAVATTU),
	SOLUONG int not null,
	GIATHANH int not null,
	MAPHIEUNHAP int FOREIGN KEY REFERENCES PHIEUNHAP(MAPHIEUNHAP),
)

create table PHIEUMUON(
	MAPHIEUMUON int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	MANHANVIEN int FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN),
	MACONGNHAN int FOREIGN KEY REFERENCES CONGNHAN(MACONGNHAN),
	NGAYMUON date not null,
	NGAYTRA date not null,
	MACONGTRINH int FOREIGN KEY REFERENCES CONGTRINH(MACONGTRINH),
	MATRANGTHAI int FOREIGN KEY REFERENCES TRANGTHAIPHIEU(MATRANGTHAI),
	GHICHU nvarchar(max)
)

create table CHITIETPHIEUMUON(
	MAVATTU int FOREIGN KEY REFERENCES VATTU(MAVATTU),
	SOLUONG int not null,
	MAPHIEUMUON int FOREIGN KEY REFERENCES PHIEUMUON(MAPHIEUMUON),
)

create table PHIEUTRA(
	MAPHIEUTRA int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	MANHANVIEN int FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN),
	MACONGNHAN int FOREIGN KEY REFERENCES CONGNHAN(MACONGNHAN),
	MAPHIEUMUON int FOREIGN KEY REFERENCES PHIEUMUON(MAPHIEUMUON),
	NGAYTRA date not null,
	MATRANGTHAI int FOREIGN KEY REFERENCES TRANGTHAIPHIEU(MATRANGTHAI),
	GHICHU nvarchar(max)
)


create table CHITIETPHIEUTRA(
	MAVATTU int FOREIGN KEY REFERENCES VATTU(MAVATTU),
	SOLUONG int not null,
	MAPHIEUTRA int FOREIGN KEY REFERENCES PHIEUTRA(MAPHIEUTRA),
)


create table PHIEUCHUYENKHO(
	MAPHIEUCHUYENKHO int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	MANHANVIEN int FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN),
	MAKHO int FOREIGN KEY REFERENCES KHO(MAKHO),
	THOIGIAN date not null,
	MATRANGTHAI int FOREIGN KEY REFERENCES TRANGTHAIPHIEU(MATRANGTHAI),
	GHICHU nvarchar(max)
)


create table CHITIETPHIEUCHUYENKHO(
	MAVATTU int FOREIGN KEY REFERENCES VATTU(MAVATTU),
	SOLUONG int not null,
	MAPHIEUCHUYENKHO int FOREIGN KEY REFERENCES PHIEUCHUYENKHO(MAPHIEUCHUYENKHO),
)





